### ISSUE TITLE
Example with parameters

### ISSUE THREAD

**Issue by c2id-support** [adamashton/json-rpc-csharp#7]
Hi Adam,

Could you please add a simple example how to pass parameters (named or positional) with the JSON-RPC 2.0 request? It is not immediately obvious for us how to do that.

Thanks,

**Comment by adamashton** [comment]
Hi,

I updated the README with some examples for you. Hope this helps.

https://github.com/adamashton/json-rpc-csharp/commit/329d737fd6bd4245b4adb625b3cfebfda952e7f1

Adam

**Comment by c2id-support** [comment]
Brilliant, thanks a lot!
